### ISSUE TITLE
Toolboxes necessary to launch all scripts

### ISSUE THREAD

**Issue by DanielePucci** [robotology-playground/torque-control-params-estimation#26]
Which MATLAB toolboxes are necessary to launch all scripts used by the torque-control-params-estimation tool? @lornat75 @randaz81

**Comment by rbonghi** [comment]
To start torque-control-params-estimation are necessary:
- Matlab
- Simulink
- WBI-Toolbox

**Comment by DanielePucci** [comment]
Thanks.

**Comment by miggia** [comment]
Does the whole pipeline work both on Linux and Windows?

**Comment by rbonghi** [comment]
If the WBI works on windows, there should be no problem, though I tried only on mac/linux.

**Comment by traversaro** [comment]
Some aspects of the windows installation should be tested, it will be probably one day of work.
