### ISSUE TITLE
Add automatic append JOINT_FRICTION

### ISSUE THREAD

**Issue by rbonghi** [robotology-playground/torque-control-params-estimation#3]
I would like to append in `codyco-superbuild/build/install/share/codyco/robots/`NAME_ROBOT`/yarpWholeBodyInterface.ini`
JOINT_FRICTION to test new configurations

**Comment by traversaro** [comment]
What do you want to modify? The joints actuated by the WBI-Toolbox? That should be possible without hacks.

**Comment by rbonghi** [comment]
> What do you want to modify?

The `yarpWholeBodyInterface.ini` on **build** directory. If I add on build directory I don't believe to create problems with other projects.

> The joints actuated by the WBI-Toolbox? That should be possible without hacks.

I think to add a temporary list of joints to read by matlab.

**Comment by rbonghi** [comment]
Dump from `libraries/yarpWholeBodyInterface/app/robots/`**NAME ROBOT**`/yarpWholeBodyInterface.ini`

Add JOINT_FRICTION and save in:
`build/install/share/codyco/robots/`**NAME ROBOT**`/yarpWholeBodyInterface.ini`

Solved 928b25ffe6aa562186b857c62e0da9d0b9c90bb3
